export type InputType = "chip-single" | "chip-multi" | "free-text";

export interface QuestionOption {
  value: string;
  labelEn: string;
  labelEs: string;
}

export interface Question {
  id: string;
  field: string;
  layerEn: string;
  layerEs: string;
  domain: string;
  en: string;
  es: string;
  helperEn?: string;
  helperEs?: string;
  inputType: InputType;
  options?: QuestionOption[];
  required: boolean;
}

export const QUESTION_BANK: Question[] = [
  {
    id: "Q-01",
    field: "industry",
    layerEn: "CONTEXT",
    layerEs: "CONTEXTO",
    domain: "Industry",
    en: "Welcome. I’m your ROBO AI analyst. Let’s map your business in about 12 minutes. What industry does your business operate in?",
    es: "Bienvenido. Soy tu analista de ROBO AI. Vamos a mapear tu negocio en unos 12 minutos. ¿En qué industria opera tu negocio?",
    helperEn: "Pick the closest match — we’ll refine later",
    helperEs: "Elige la opción más cercana — la refinaremos después",
    inputType: "chip-single",
    options: [
      {
        value: "logistics_supply_chain",
        labelEn: "Logistics & Supply Chain",
        labelEs: "Logística y cadena de suministro",
      },
      {
        value: "healthcare_wellness",
        labelEn: "Healthcare & Wellness",
        labelEs: "Salud y bienestar",
      },
      {
        value: "real_estate_property",
        labelEn: "Real Estate & Property",
        labelEs: "Bienes raíces y propiedad",
      },
      {
        value: "retail_ecommerce",
        labelEn: "Retail & E-commerce",
        labelEs: "Retail y comercio electrónico",
      },
      {
        value: "professional_services",
        labelEn: "Professional Services",
        labelEs: "Servicios profesionales",
      },
      {
        value: "finance_accounting",
        labelEn: "Finance & Accounting",
        labelEs: "Finanzas y contabilidad",
      },
      {
        value: "manufacturing_operations",
        labelEn: "Manufacturing & Operations",
        labelEs: "Manufactura y operaciones",
      },
      {
        value: "technology_saas",
        labelEn: "Technology & SaaS",
        labelEs: "Tecnología y SaaS",
      },
      {
        value: "education_training",
        labelEn: "Education & Training",
        labelEs: "Educación y formación",
      },
      { value: "legal", labelEn: "Legal", labelEs: "Legal" },
      {
        value: "hospitality_events",
        labelEn: "Hospitality & Events",
        labelEs: "Hospitalidad y eventos",
      },
      { value: "other", labelEn: "Other", labelEs: "Otro" },
    ],
    required: true,
  },
  {
    id: "Q-01B",
    field: "industry_other_details",
    layerEn: "CONTEXT",
    layerEs: "CONTEXTO",
    domain: "Industry",
    en: "You selected Other. What best describes your business type (industry/niche) and what do you sell (and to whom)?",
    es: "Seleccionaste Otro. ¿Qué describe mejor tu tipo de negocio (industria/nicho) y qué vendes (y a quién)?",
    helperEn: "Example: “Commercial cleaning for medical clinics in Toronto”",
    helperEs: "Ejemplo: “Limpieza comercial para clínicas médicas en Toronto”",
    inputType: "free-text",
    required: true,
  },
  {
    id: "Q-02",
    field: "team_size",
    layerEn: "CONTEXT",
    layerEs: "CONTEXTO",
    domain: "Team Size",
    en: "How many people are on your team today?",
    es: "¿Cuántas personas forman tu equipo hoy?",
    inputType: "chip-single",
    options: [
      { value: "1", labelEn: "Just me", labelEs: "Solo yo" },
      { value: "2-5", labelEn: "2–5", labelEs: "2–5" },
      { value: "6-20", labelEn: "6–20", labelEs: "6–20" },
      { value: "21-50", labelEn: "21–50", labelEs: "21–50" },
      { value: "51-200", labelEn: "51–200", labelEs: "51–200" },
      { value: "200+", labelEn: "200+", labelEs: "200+" },
    ],
    required: true,
  },
  {
    id: "Q-03",
    field: "revenue_range",
    layerEn: "CONTEXT",
    layerEs: "CONTEXTO",
    domain: "Revenue",
    en: "Roughly what revenue range are you in?",
    es: "Aproximadamente, ¿en qué rango de ingresos estás?",
    inputType: "chip-single",
    options: [
      { value: "<10k", labelEn: "Under $10k / mo", labelEs: "Menos de $10k / mes" },
      { value: "10-50k", labelEn: "$10k–$50k / mo", labelEs: "$10k–$50k / mes" },
      { value: "50-200k", labelEn: "$50k–$200k / mo", labelEs: "$50k–$200k / mes" },
      { value: "200k-1m", labelEn: "$200k–$1M / mo", labelEs: "$200k–$1M / mes" },
      { value: "1m+", labelEn: "$1M+ / mo", labelEs: "$1M+ / mes" },
    ],
    required: true,
  },
  {
    id: "Q-04",
    field: "core_ops",
    layerEn: "OPERATIONS & STACK",
    layerEs: "OPERACIONES Y STACK",
    domain: "Operations",
    en: "At a high level, what does a typical week of operations look like for your team?",
    es: "A grandes rasgos, ¿cómo se ve una semana típica de operaciones para tu equipo?",
    inputType: "free-text",
    required: true,
  },
  {
    id: "Q-05",
    field: "top_time_cost",
    layerEn: "OPERATIONS & STACK",
    layerEs: "OPERACIONES Y STACK",
    domain: "Time Cost",
    en: "What is the single highest-cost task (time or money) your business does repeatedly?",
    es: "¿Cuál es la tarea de mayor costo (tiempo o dinero) que tu negocio repite con frecuencia?",
    inputType: "free-text",
    required: true,
  },
  {
    id: "Q-06",
    field: "existing_tools",
    layerEn: "OPERATIONS & STACK",
    layerEs: "OPERACIONES Y STACK",
    domain: "Tools",
    en: "Which tools does your team rely on day-to-day?",
    es: "¿Qué herramientas usa tu equipo en el día a día?",
    inputType: "chip-multi",
    options: [
      { value: "excel", labelEn: "Excel / Sheets", labelEs: "Excel / Sheets" },
      { value: "whatsapp", labelEn: "WhatsApp", labelEs: "WhatsApp" },
      { value: "quickbooks", labelEn: "QuickBooks", labelEs: "QuickBooks" },
      { value: "salesforce", labelEn: "Salesforce", labelEs: "Salesforce" },
      { value: "hubspot", labelEn: "HubSpot", labelEs: "HubSpot" },
      { value: "slack", labelEn: "Slack", labelEs: "Slack" },
      { value: "notion", labelEn: "Notion", labelEs: "Notion" },
      { value: "shopify", labelEn: "Shopify", labelEs: "Shopify" },
      { value: "gmail", labelEn: "Email (Gmail/Outlook)", labelEs: "Email (Gmail/Outlook)" },
      { value: "erp", labelEn: "ERP", labelEs: "ERP" },
      { value: "crm_other", labelEn: "Other CRM", labelEs: "Otro CRM" },
      { value: "none", labelEn: "None / Paper", labelEs: "Ninguno / Papel" },
    ],
    required: true,
  },
  {
    id: "Q-07",
    field: "data_situation",
    layerEn: "OPERATIONS & STACK",
    layerEs: "OPERACIONES Y STACK",
    domain: "Data",
    en: "Where does the data live that runs your operations?",
    es: "¿Dónde vive la información que impulsa tus operaciones?",
    inputType: "chip-single",
    options: [
      { value: "spreadsheets", labelEn: "Mostly spreadsheets", labelEs: "Principalmente hojas de cálculo" },
      { value: "crm", labelEn: "CRM", labelEs: "CRM" },
      { value: "erp", labelEn: "ERP", labelEs: "ERP" },
      { value: "support", labelEn: "Support desk", labelEs: "Mesa de ayuda" },
      { value: "database", labelEn: "Database / warehouse", labelEs: "Base de datos / warehouse" },
      { value: "mixed", labelEn: "Mixed / multiple", labelEs: "Mixto / múltiples" },
      { value: "not_sure", labelEn: "Not sure", labelEs: "No estoy seguro/a" },
    ],
    required: true,
  },
  {
    id: "Q-08",
    field: "bottleneck",
    layerEn: "BOTTLENECK & RISK",
    layerEs: "CUELLO DE BOTELLA Y RIESGO",
    domain: "Bottleneck",
    en: "What is the single biggest operational bottleneck right now?",
    es: "¿Cuál es el mayor cuello de botella operativo en este momento?",
    inputType: "free-text",
    required: true,
  },
  {
    id: "Q-09",
    field: "decision_speed",
    layerEn: "BOTTLENECK & RISK",
    layerEs: "CUELLO DE BOTELLA Y RIESGO",
    domain: "Decision Speed",
    en: "How quickly can you spot problems or performance changes in the business?",
    es: "¿Qué tan rápido puedes detectar problemas o cambios de rendimiento en el negocio?",
    inputType: "chip-single",
    options: [
      { value: "real_time", labelEn: "Real-time / same day", labelEs: "En tiempo real / mismo día" },
      { value: "1-2_days", labelEn: "1–2 days", labelEs: "1–2 días" },
      { value: "weekly", labelEn: "Weekly", labelEs: "Semanal" },
      { value: "monthly", labelEn: "Monthly", labelEs: "Mensual" },
      { value: "not_sure", labelEn: "Not sure", labelEs: "No estoy seguro/a" },
    ],
    required: true,
  },
  {
    id: "Q-10",
    field: "risk_areas",
    layerEn: "BOTTLENECK & RISK",
    layerEs: "CUELLO DE BOTELLA Y RIESGO",
    domain: "Risks",
    en: "Which risk areas matter most right now?",
    es: "¿Qué áreas de riesgo importan más ahora mismo?",
    helperEn: "Select all that apply",
    helperEs: "Selecciona todas las que apliquen",
    inputType: "chip-multi",
    options: [
      { value: "compliance", labelEn: "Compliance", labelEs: "Cumplimiento" },
      { value: "security", labelEn: "Security", labelEs: "Seguridad" },
      { value: "cash_flow", labelEn: "Cash flow", labelEs: "Flujo de caja" },
      { value: "customer_churn", labelEn: "Customer churn", labelEs: "Pérdida de clientes" },
      { value: "quality", labelEn: "Quality issues", labelEs: "Problemas de calidad" },
      { value: "ops_errors", labelEn: "Operational errors", labelEs: "Errores operativos" },
      { value: "missed_leads", labelEn: "Missed leads", labelEs: "Leads perdidos" },
      { value: "fraud", labelEn: "Fraud", labelEs: "Fraude" },
      { value: "safety", labelEn: "Safety", labelEs: "Seguridad (física)" },
      { value: "other", labelEn: "Other", labelEs: "Otro" },
    ],
    required: true,
  },
  {
    id: "Q-11",
    field: "prior_ai_experience",
    layerEn: "READINESS & CLOSING",
    layerEs: "LISTO PARA IMPLEMENTAR Y CIERRE",
    domain: "Prior AI",
    en: "Have you tried AI tools or automation before?",
    es: "¿Has probado herramientas de IA o automatización antes?",
    inputType: "chip-single",
    options: [
      { value: "yes", labelEn: "Yes", labelEs: "Sí" },
      { value: "tried", labelEn: "Tried but abandoned", labelEs: "Probé pero lo abandoné" },
      { value: "no", labelEn: "No", labelEs: "No" },
    ],
    required: true,
  },
  {
    id: "Q-12",
    field: "budget_comfort",
    layerEn: "READINESS & CLOSING",
    layerEs: "LISTO PARA IMPLEMENTAR Y CIERRE",
    domain: "Budget",
    en: "What monthly budget feels comfortable for an AI solution?",
    es: "¿Qué presupuesto mensual te resulta cómodo para una solución de IA?",
    inputType: "chip-single",
    options: [
      { value: "<500", labelEn: "Under $500/mo", labelEs: "Menos de $500/mes" },
      { value: "500-2k", labelEn: "$500–$2,000/mo", labelEs: "$500–$2,000/mes" },
      { value: "2k-5k", labelEn: "$2k–$5k/mo", labelEs: "$2k–$5k/mes" },
      { value: "5k-15k", labelEn: "$5k–$15k/mo", labelEs: "$5k–$15k/mes" },
      { value: "15k+", labelEn: "$15k+/mo", labelEs: "$15k+/mes" },
    ],
    required: true,
  },
  {
    id: "Q-13",
    field: "urgency_flag",
    layerEn: "READINESS & CLOSING",
    layerEs: "LISTO PARA IMPLEMENTAR Y CIERRE",
    domain: "Urgency",
    en: "How urgent is this for you?",
    es: "¿Qué tan urgente es esto para ti?",
    inputType: "chip-single",
    options: [
      { value: "0-30d", labelEn: "ASAP (0–30 days)", labelEs: "Lo antes posible (0–30 días)" },
      { value: "this_quarter", labelEn: "This quarter", labelEs: "Este trimestre" },
      { value: "next_6_months", labelEn: "Next 6 months", labelEs: "Próximos 6 meses" },
      { value: "exploring", labelEn: "Just exploring", labelEs: "Solo explorando" },
    ],
    required: true,
  },
  {
    id: "Q-14",
    field: "success_definition",
    layerEn: "READINESS & CLOSING",
    layerEs: "LISTO PARA IMPLEMENTAR Y CIERRE",
    domain: "Success",
    en: "Define success: 6 months from now, what would make you say this was worth it?",
    es: "Define el éxito: dentro de 6 meses, ¿qué te haría decir que valió la pena?",
    inputType: "free-text",
    required: true,
  },
  {
    id: "Q-15",
    field: "website_url",
    layerEn: "READINESS & CLOSING",
    layerEs: "LISTO PARA IMPLEMENTAR Y CIERRE",
    domain: "Website",
    en: "What is your business website URL? (We’ll use it for silent enrichment)",
    es: "¿Cuál es la URL de tu sitio web? (La usaremos para enriquecer el análisis)",
    inputType: "free-text",
    required: false,
  },
];

export function getQuestionById(id: string): Question | undefined {
  return QUESTION_BANK.find((q) => q.id === id);
}
